depthealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^reportviewing/', include('reportviewing.urls', namespace="reportviewing")),
    url(r'^reportinput/', include('reportinput.urls', namespace="reportinput")),
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^admin/', include(admin.site.urls)),
]

faq/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^category/',views.category, name='category'),
    url(r'^(?P<category_id>[0-9]+)/questions', views.faq, name='questions')
]

login/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^$',views.loginscreen, name='login'),
    url(r'^landingpage',views.landingpage, name='landingpage'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^reset', views.resetpassword, name='reset')
]

urlpatterns += staticfiles_urlpatterns()

register/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = [
    url(r'^userlist', views.userfilter,name='userlist'),
    url(r'^(?P<person_id>[0-9]+)/modifyuser',views.modifyuser, name='modifyuser'),
    url(r'^(?P<facility_id>[0-9]+)/modify',views.modifyfacility, name='modify'),
    url(r'list', views.facilitylist, name='facilitylist'),
    url(r'facilityinput',views.facility, name='facilityinput'),
    url(r'createuser', views.createuser,name='createuser'),
    url(r'user', views.username,name='user'),
    url(r'^(?P<facility_id>[0-9]+)/facilitylanding', views.facilitylanding,name='facilitylanding')
]

reportinput/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = [
    url(r'epi12a',views.epi12a, name='epi12a'),
    url(r'epi12b',views.epi12b, name='epi12b'),
    url(r'landing12a', views.landing12a, name='landing12a'),
    url(r'landing12b', views.landing12b, name='landing12b'),
    url(r'complete', views.complete, name='complete'),
    url(r'^(?P<student_id>[0-9]+)/update12a', views.update12a, name='update12a'),
    url(r'^(?P<student_id>[0-9]+)/update12b', views.update12b, name='update12b')
]

reportviewing/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns =[
    url(r'^(?P<student_id>[0-9]+)/removefromreport', views.removefromreport, name='removefromreport'),
    url(r'reportsbydate',views.reportsbydate,name='date'),
    url(r'^(?P<report_id>[0-9]+)/$',views.schoolreport,name='schoolreport'),
    url(r'^(?P<report_id>[0-9]+)/csva', views.createschoolcsva, name='csva'),
    url(r'^(?P<report_id>[0-9]+)/csvb', views.createschoolcsvb, name='csvb'),
    url(r'master12b', views.createmasterlist12b, name='master12b'),
    url(r'master12a', views.createmasterlist12a, name='master12a'),
    url(r'^students', views.listofstudents, name='students'),
    url(r'^studentfilter',views.studentfilter, name='studentfilter'),
    url(r'12apdf', views.epi12apdf, name='epi12apdf'),
    url(r'12bpdf', views.epi12bpdf, name='epi12bpdf'),
    url(r'removehighest', views.removehighestgrade, name='removehighest'),
    url(r'^importstudent/(?P<student_id>[0-9]+)', views.importstudent, name='importstudent'),
    url(r'importview', views.importview, name='importview')
]

support/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = [
    url(r'createticket', views.createrequest, name='create'),
    url(r'openticket', views.viewrequests, name='open'),
    url(r'^r(?P<r_id>[0-9]+)/updateticket', views.updatesupport, name='update'),
    url(r'^r(?P<r_id>[0-9]+)/closeticket', views.closesupport, name='close')
]

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from __future__ import unicode_literals
from django import forms
from register.models import User, Person
from django.forms import PasswordInput
class Login(forms.Form):
    username = forms.CharField(max_length=255)
    password = forms.CharField(widget=PasswordInput(), max_length=50)

    class Meta:
        model = User

class ResetPassword(forms.Form):
    username = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    old_password = forms.CharField(max_length=50, widget=forms.PasswordInput(attrs={'class' : 'form-control p30'}))
    new_password1 = forms.CharField(label="New Password", max_length=50, widget=forms.PasswordInput(attrs={'class' : 'form-control p30'}))
    new_password2 = forms.CharField(label="Confirm New Password", max_length=50, widget=forms.PasswordInput(attrs={'class' : 'form-control p30'}))

    class Meta:
        model = User

login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User as uauth
from django.core.urlresolvers import reverse
from .forms import Login, ResetPassword
from register.models import User as u, Person, Facility
from register.views import passwordcheck

# Create your views here.

def loginscreen(request):

    if request.method == 'POST':
        form = Login(request.POST)
        if form.is_valid():
            try:
                username = u.objects.get(pk=form.cleaned_data['username'])
                person = Person.objects.get(email=username.username)
                user = authenticate(username=username, password = form.cleaned_data['password'])
                if user:
                    if user.is_active:
                        login(request, user)
                        request.session['personpk'] = person.pk
                        request.session['role'] = person.role_id
                        request.session['fac'] = person.facility_id
                        if person.role_id == 1:
                            request.session['schoolfilter'] = 'all'
                            request.session['island'] = 'all'
                            request.session['district'] = 'all'
                        if(person.facility_id > 0):
                            f = Facility.objects.get(pk = person.facility_id)
                            request.session['hasprek'] = f.has_pre_k
                            request.session['onlyprk'] = f.is_only_pre_k
                        request.session['lname'] = 'all'
                        request.session['ulname'] = 'all'
                    if person.verified:
                        username = u.objects.get(pk = person.email_id)
                        if username.password == 'password':
                            return HttpResponseRedirect(reverse('login:reset'))
                        else:
                            return render(request,'login/landingpage.html', {'p':person})
                else:
                    HttpResponseRedirect('')
            except u.DoesNotExist:
                HttpResponseRedirect('')

    else:
        form = Login()
    return render(request,'login/login.html',{'form':form,})

@login_required
def landingpage(request):
    p = Person.objects.get(pk = request.session['personpk'])
    return render(request,'login/landingpage.html', {'p':p,})

def resetpassword(request):
    form = ResetPassword()
    if request.method == 'POST':
        form = ResetPassword(request.POST)
        if form.is_valid():
            pw1 = form.cleaned_data['new_password1']
            pw2 = form.cleaned_data['new_password2']
            oldpw = form.cleaned_data['old_password']
            pwcheck = passwordcheck(pw1)
            user = u.objects.get(pk = form.cleaned_data['username'])
            if user.password == oldpw:
                if pw1 == pw2 and pwcheck != 1:
                    user.password = form.cleaned_data['new_password2']
                    user.save()
                    auth_user = uauth.objects.get(username = form.cleaned_data['username'])
                    auth_user.set_password(pw1)
                    auth_user.save()
                    return render(request, 'login/login.html',{'form':Login(),})
    return render(request, 'login/reset.html', {'form':form,})

def logout_view(request):
    logout(request)
    return render(request,'login/login.html',{'form':Login()})

login/templates/login/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/borders.css' %}" rel="stylesheet" media="screen">
	<link href="{% static 'css/depthealth.css' %}" rel="stylesheet" media="screen">
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	  </div>

	  <a class="navbar-brand" href="#">&nbsp;</a>

	  <div class="navbar-collapse collapse">
	    <img src="{% static "login/header.gif" %}" alt="Header" />
	    <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'reportviewing:epi12apdf' %}">EPI12A PDF</a></li>
            <li><a href="{% url 'reportviewing:epi12bpdf' %}">EPI12B PDF</a></li>
	        <li><a href="{% url 'faq:category' %}">FAQ</a></li>
	        <li><a href="{% url 'login:logout' %}">Logout</a></li>
	    </ul>
	  </div>
	</nav>
    {% block header %}
    {% endblock %}
    <nav class="collapse navbar-inverse navbar-collapse bs-navbar-collapse" role="navigation">
      <div class="container">
        {% csrf_token %}

          <ul class="nav navbar-nav">
          {% if request.session.role == 1 %}
            <li><a href="{% url 'register:facilitylist' %}">Manage Facility</a></li>
            {% endif %}
              {% if request.session.role == 2 %}
                  <li><a href="{% url 'register:facilitylanding' request.session.fac %}">Manage Facility</a></li>
              {% endif %}
          {% if request.session.role == 1 or request.session.role == 2%}
              <li><a href="{% url 'register:userlist' %}">Manage User's</a></li>
          {% endif %}
            {% if request.session.hasprek == 1 and request.session.role != 1 %}
             <li><a href="{% url 'reportinput:landing12a' %}">Create EPI12A</a></li>
            {% endif %}
            {% if request.session.onlyprk == 0 and request.session.role != 1 %}
                <li><a href="{% url 'reportinput:landing12b' %}">Create EPI12B</a></li>
            {% endif %}
            {% if request.session.role != 1 %}
                <li><a href="{% url 'reportviewing:date' %}">View Reports</a></li>
            {% endif %}
            {% csrf_token %}
              <li><a href="{% url 'support:open' %}">Support Request</a></li>
            <li><a href="{% url 'reportviewing:studentfilter' %}">Student List</a> </li>
          <li><a href="{% url 'login:landingpage' %}">Home</a> </li>
        </ul>
      </div>
    </nav>

	<div class="container">
    {% block content %}
    {% endblock %}
	</div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright 2015 State of Hawaii Department of Health Developed by: Hawai'i Pacific University
Version 1.0 Build 2015</p>
      </div>
    </footer>
</body>
</html>

login/templates/login/landingpage.html
{% extends 'login/base.html' %}
{% load staticfiles %}
{% block header %}
    <p align="center" >Welcome {{ p }}</p>
{% endblock %}
{% block content %}
<img src="{% static "login/smiling_child.jpg" %}" style="width: 60%">
{% endblock %}

login/templates/login/login.html
{% extends "login/loginbase.html" %}

{% block content %}
    <div class="alert alert-info" role="alert">
		Welcome to the Hawaii State Department of Health online immunization reporting system.
		Please select your school/facility and password. Selecting a district will return only those schools/facilities belonging to that district.
		This may help you find your school/facility.
		<strong>If you don't see your school or facility listed below</strong>, please contact the Immunization Branch at <strong>586-8300</strong> for technical assistance.
	</div>
<fieldset class="login">
    <legend class="login">Login</legend>
    <form action = "/login/" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</fieldset>
    <a href="{% url 'register:user' %}">Create User</a>
    |
    <a href="{% url 'login:reset' %}">Reset Password</a>
    </table>
{% endblock %}

login/templates/login/loginbase.html
{% load staticfiles %}

<html lang="en">
<head>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/borders.css' %}" rel="stylesheet" media="screen">
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	  </div>

	  <a class="navbar-brand" href="#">&nbsp;</a>

	  <div class="navbar-collapse collapse">
	    <img src="{% static "login/header.gif" %}" alt="Header" />
	    <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'reportviewing:epi12apdf' %}">EPI12A PDF</a></li>
            <li><a href="{% url 'reportviewing:epi12bpdf' %}">EPI12B PDF</a></li>
	        <li><a href="{% url 'faq:category' %}">FAQ</a></li>
	    </ul>
	  </div>
	</nav>

	<div class="container">
    {% block content %}
    {% endblock %}
	</div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright 2015 State of Hawaii Department of Health Developed by: Hawai'i Pacific University
Version 1.0 Build 2015</p>
      </div>
    </footer>
</body>
</html>

login/templates/login/otherbase.html
{% load staticfiles %}

<html lang="en">
<head>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/borders.css' %}" rel="stylesheet" media="screen">
	<link href="{% static 'css/depthealth.css' %}" rel="stylesheet" media="screen">
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	  </div>

	  <a class="navbar-brand" href="#">&nbsp;</a>

	  <div class="navbar-collapse collapse">
	    <img src="{% static "login/header.gif" %}" alt="Header" />
	    <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'reportviewing:epi12apdf' %}">EPI12A PDF</a></li>
            <li><a href="{% url 'reportviewing:epi12bpdf' %}">EPI12B PDF</a></li>
	        <li><a href="{% url 'faq:category' %}">FAQ</a></li>
	    </ul>
	  </div>
	</nav>


	<div class="container">
    {% block content %}
    {% endblock %}
	</div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">Copyright 2015 State of Hawaii Department of Health Developed by: Hawai'i Pacific University
Version 1.0 Build 2015</p>
      </div>
    </footer>
</body>
</html>

login/templates/login/reset.html
{% extends 'login/otherbase.html' %}
{% block content %}
<fieldset class="login">
    <legend class="login">Reset Password</legend>
    <form action="" method="post">
    {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit" value="Submit" class="btn btn-primary">
    </form>
</fieldset>
{% endblock %}