depthealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^reportviewing/', include('reportviewing.urls', namespace="reportviewing")),
    url(r'^reportinput/', include('reportinput.urls', namespace="reportinput")),
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^admin/', include(admin.site.urls)),
]

faq/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^category/',views.category, name='category'),
    url(r'^(?P<category_id>[0-9]+)/questions', views.faq, name='questions')
]

login/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^$',views.loginscreen, name='login'),
    url(r'^landingpage',views.landingpage, name='landingpage'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^reset', views.resetpassword, name='reset')
]

urlpatterns += staticfiles_urlpatterns()

register/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = [
    url(r'^userlist', views.userfilter,name='userlist'),
    url(r'^(?P<person_id>[0-9]+)/modifyuser',views.modifyuser, name='modifyuser'),
    url(r'^(?P<facility_id>[0-9]+)/modify',views.modifyfacility, name='modify'),
    url(r'list', views.facilitylist, name='facilitylist'),
    url(r'facilityinput',views.facility, name='facilityinput'),
    url(r'createuser', views.createuser,name='createuser'),
    url(r'user', views.username,name='user'),
    url(r'^(?P<facility_id>[0-9]+)/facilitylanding', views.facilitylanding,name='facilitylanding')
]

reportviewing/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns =[
    url(r'^(?P<student_id>[0-9]+)/removefromreport', views.removefromreport, name='removefromreport'),
    url(r'reportsbydate',views.reportsbydate,name='date'),
    url(r'^(?P<report_id>[0-9]+)/$',views.schoolreport,name='schoolreport'),
    url(r'^(?P<report_id>[0-9]+)/csva', views.createschoolcsva, name='csva'),
    url(r'^(?P<report_id>[0-9]+)/csvb', views.createschoolcsvb, name='csvb'),
    url(r'master12b', views.createmasterlist12b, name='master12b'),
    url(r'master12a', views.createmasterlist12a, name='master12a'),
    url(r'^students', views.listofstudents, name='students'),
    url(r'^studentfilter',views.studentfilter, name='studentfilter'),
    url(r'12apdf', views.epi12apdf, name='epi12apdf'),
    url(r'12bpdf', views.epi12bpdf, name='epi12bpdf'),
    url(r'removehighest', views.removehighestgrade, name='removehighest'),
    url(r'^importstudent/(?P<student_id>[0-9]+)', views.importstudent, name='importstudent'),
    url(r'importview', views.importview, name='importview')
]

register/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Facility, Person, Role, Island, District, User, Enrollment

class CreateFacility(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class' : 'form-control p60'}))
    street = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class' : 'form-control p60'}))
    zip = forms.IntegerField(max_value=99999, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    city = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    phone = forms.IntegerField(max_value=9999999999, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    fax = forms.IntegerField(max_value=9999999999, required=False, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    email = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    has_pre_k = forms.BooleanField(required=False)
    is_only_pre_k = forms.BooleanField(required=False)
    island = forms.ModelChoiceField(Island.objects.all())
    district = forms.ModelChoiceField(District.objects.all())
    lowest_grade = forms.ModelChoiceField(Enrollment.objects.all())
    highest_grade = forms.ModelChoiceField(Enrollment.objects.all())

    class Meta:
        model = Facility

class CreateUser(forms.Form):
    fname = forms.CharField(max_length=50)
    mname = forms.CharField(max_length=50, required=False)
    lname = forms.CharField(max_length=50)
    phone = forms.IntegerField(max_value=9999999999)
    fax = forms.IntegerField(max_value=9999999999, required=False)
    title = forms.CharField(max_length=50, required=False)
    facility = forms.ModelChoiceField(Facility.objects.exclude(pk = 1).order_by('name'))
    role = forms.ModelChoiceField(Role.objects.exclude(id = 1))
    class Meta:
        model = Person

class ModifyUser(forms.Form):
    fname = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class' : 'form-control p60'}))
    mname = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'class' : 'form-control p60'}))
    lname = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    phone = forms.IntegerField(max_value=9999999999, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    fax = forms.IntegerField(max_value=99999999999, required=False, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    title = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    user = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    password = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class' : 'form-control p30'}))
    facility = forms.ModelChoiceField(Facility.objects.all().order_by('name'), required=False)
    role = forms.ModelChoiceField(Role.objects.all(), required=False)
    verify = forms.BooleanField(required=False)

class Username(forms.Form):
    user = forms.EmailField(max_length=255, widget=forms.TextInput(attrs={'class' : 'form-control p60'}))
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class' : 'form-control p60'}))
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class' : 'form-control p60'}))
    class Meta:
        model = User

class FacilityFilter(forms.Form):
    name = forms.CharField(required=False)
    island = forms.ModelChoiceField(Island.objects.all(), required=False)
    district = forms.ModelChoiceField(District.objects.all(), required=False)

register/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .forms import CreateFacility, CreateUser, Username, ModifyUser, FacilityFilter
from .models import  Facility, District, Role, User, Person, Enrollment, Island
from django.contrib.auth.models import User as uauth
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from reportviewing.views import StudentFilter
import operator

# Create your views here.

@login_required
def facility(request):
    if request.method =='POST':
        form = CreateFacility(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            street = form.cleaned_data['street']
            zip = form.cleaned_data['zip']
            city = form.cleaned_data['city']
            has_pre_k = form.cleaned_data['has_pre_k']
            is_only_pre_k = form.cleaned_data['is_only_pre_k']
            phone = form.cleaned_data['phone']
            fax = form.cleaned_data['fax']
            email = form.cleaned_data['email']
            district = District.objects.get(name = form.cleaned_data['district'])
            lowest_g = Enrollment.objects.get(name = form.cleaned_data['lowest_grade'])
            highest_g = Enrollment.objects.get(name = form.cleaned_data['highest_grade'])
            f = Facility(name=name,street=street,zip=zip,city=city,has_pre_k=has_pre_k,is_only_pre_k=is_only_pre_k, phone=phone, fax=fax,email=email)
            f.lowest_grade_id = lowest_g.pk
            f.highest_grade_id = highest_g.pk
            f.district_id = district.pk
            f.count = 0
            f.save()
            return HttpResponseRedirect(reverse('login:landingpage'))
    else:
        form = CreateFacility()
    return render(request,'register/facilityinput.html',{'form':form,})

@login_required
def facilitylist(request):
    form = FacilityFilter()
    if request.session['schoolfilter'] == 'all':
        object_list = Facility.objects.exclude(pk=1).order_by('name')
    else:
        object_list = Facility.objects.filter(name__icontains=request.session['schoolfilter']).order_by('name')
    if request.session['district'] != 'all':
        d = District.objects.get(pk = request.session['district'])
        object_list = object_list.filter(district_id = d.pk)
    if request.session['island'] != 'all':
        i = Island.objects.get(pk = request.session['island'] )
        districts = District.objects.filter(island_id=i.pk)
        object_list = object_list.filter(reduce(operator.or_,[Q(district_id = d.pk) for d in districts]))

    if request.method=='POST':
        form = FacilityFilter(request.POST)
        if form.is_valid():
            if form.cleaned_data['name'] is None:
                request.session['schoolfilter'] = 'all'
            else:
                request.session['schoolfilter'] = form.cleaned_data['name']
            if form.cleaned_data['island'] is None:
                request.session['island'] = 'all'
            else:
                request.session['island'] = Island.objects.get(pk =
form.cleaned_data['island']).pk
            if form.cleaned_data['district'] is None:
                request.session['district'] = 'all'
            else:
                request.session['district'] = District.objects.get(name= form.cleaned_data['district']).pk
            return HttpResponseRedirect(reverse('register:facilitylist'))
    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')
    try:
        fac = paginator.page(page)
    except PageNotAnInteger:
        fac = paginator.page(1)
    except EmptyPage:
        fac = paginator.page(paginator.num_pages)

    return render(request,'register/facility_list.html',{'form':form, 'object_list':fac})



def username(request):
    if request.method == 'POST':
        form = Username(request.POST)
        if form.is_valid():
            users = User.objects.filter(pk=form.cleaned_data['user'])
            if not users:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 == password2 and passwordcheck(password1) != 1:
                    u = User(username=form.cleaned_data['user'], password=password2)
                    u.save()
                    request.session['user'] = u.pk
                    return HttpResponseRedirect(reverse('register:createuser'))
    else:
        form = Username()
    return render(request, 'register/user.html',{'form':form,})


def createuser(request):
    u = request.session['user']
    request.session['user'] = u
    if request.method =='POST':
        form = CreateUser(request.POST)
        if form.is_valid():
            fac = Facility.objects.get(name = form.cleaned_data['facility'])
            role = Role.objects.get(name = form.cleaned_data['role'])
            fname = form.cleaned_data['fname']
            mname = form.cleaned_data['mname']
            lname = form.cleaned_data['lname']
            phone = form.cleaned_data['phone']
            fax = form.cleaned_data['fax']
            title = form.cleaned_data['title']
            p = Person(fname=fname, mname=mname, lname=lname, phone=phone,fax=fax,title=title)
            p.email_id = User.objects.get(pk = u)
            p.facility_id=fac.pk
            p.role_id=role.pk
            p.save()
            uname = User.objects.get(pk = p.email_id)
            user = uauth.objects.create_user(username = uname.pk, password=uname.password, first_name = p.fname, last_name = p.lname)
            user.save()
            return HttpResponseRedirect(reverse('login:login'))
    else:
        form = CreateUser()
    return render(request, 'register/createuser.html', {'form':form,})

@login_required
def facilitylanding(request, facility_id):

    f = Facility.objects.get(pk=facility_id)
    d = District.objects.get(pk=f.district_id)
    try:
        p = Person.objects.filter(facility_id=f.pk).get(role_id=2)
    except Person.DoesNotExist:
        p = None

    if request.method == 'POST':
        request.session['inputid'] = f.pk

        if '12a' in request.POST:
                return HttpResponseRedirect(reverse('reportinput:landing12a'))
        if '12b' in request.POST:
                return HttpResponseRedirect(reverse('reportinput:landing12b'))

        if 'Med' in request.POST:
            request.session['type']=1

        if 'Rel' in request.POST:
            request.session['type']=2

        if 'Ex' in request.POST:
            request.session['type']=3

        if 'All' in request.POST:
            request.session['type']=4

        return HttpResponseRedirect(reverse('reportviewing:students'))
    else:
        return render(request, 'register/facilitylanding.html',{'f':f,'d':d,'p':p})

@login_required
def modifyfacility(request, facility_id):
    facility = Facility.objects.get(pk = facility_id)
    district = District.objects.get(pk = facility.district_id)
    if request.method == 'POST':
        form = CreateFacility(request.POST)
        if 'Delete' in request.POST:
            f = Facility.objects.get(pk = facility_id)
            f.delete()
            return HttpResponseRedirect(reverse('login:landingpage'))
        if 'Change' in request.POST:
            if form.is_valid():
                f = Facility.objects.get(pk= facility_id)
                f.name = form.cleaned_data['name']
                f.save()
                f.street = form.cleaned_data['street']
                f.save()
                f.zip = form.cleaned_data['zip']
                f.save()
                f.city = form.cleaned_data['city']
                f.save()
                f.has_pre_k = form.cleaned_data['has_pre_k']
                f.save()
                f.is_only_pre_k = form.cleaned_data['is_only_pre_k']
                f.save()
                f.phone = form.cleaned_data['phone']
                f.save()
                f.fax = form.cleaned_data['fax']
                f.save()
                f.email = form.cleaned_data['email']
                f.save()
                f.district = District.objects.get(name = form.cleaned_data['district'])
                f.save()
                f.lowest_grade = Enrollment.objects.get(name = form.cleaned_data['lowest_grade'])
                f.save()
                f.highest_grade = Enrollment.objects.get(name = form.cleaned_data['highest_grade'])
                f.save()

            return HttpResponseRedirect(reverse('login:landingpage'))

    else:
        form = CreateFacility(initial={'name':facility.name,'street':facility.street,'zip':facility.zip, 'city':facility.city, 'has_pre_k':facility.has_pre_k,'is_only_pre_k':facility.is_only_pre_k,'phone':facility.phone, 'fax':facility.fax, 'email':facility.email, 'island':district.island, 'district':facility.district, 'lowest_grade':facility.lowest_grade, 'highest_grade':facility.highest_grade})
    return render(request, 'register/modifyfac.html', {'form':form,})

@login_required
def modifyuser(request, person_id):
    person = Person.objects.get(pk = person_id)
    user = User.objects.get(pk = person.email_id)
    if request.method == 'POST':
        if 'Delete' in request.POST:
            p = Person.objects.get(pk = person_id)
            u = User.objects.get(pk = p.email_id)
            ua = uauth.objects.get(username= u.username)
            p.delete()
            u.delete()
            ua.delete()
            return HttpResponseRedirect(reverse('login:landingpage'))
        if 'Change' in request.POST:
            form = ModifyUser(request.POST)
            if form.is_valid():
                p = Person.objects.get(pk = person_id)
                u = User.objects.get(pk = person.email_id)
                u.password = form.cleaned_data['password']
                u.save()

register/templates/register/createuser.html
{% extends 'login/otherbase.html' %}

{% block content %}
<fieldset class="login">
    <legend class="login">Create User</legend>
    <form action="" method="post">
    {% csrf_token %}
    <table align="center">
        <tr>
            <td>First Name:</td>
            <td>{{ form.fname }}</td>
        </tr>
        <tr>
            <td>Middle Name:</td>
            <td>{{ form.mname }}</td>
        </tr>
        <tr>
            <td>Last Name:</td>
            <td>{{ form.lname }}</td>
        </tr>
        <tr>
            <td>Phone:</td>
            <td>{{ form.phone }}</td>
        </tr>
        <tr>
            <td>Fax:</td>
            <td>{{ form.fax }}</td>
        </tr>
        <tr>
            <td>Title</td>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <td>Facility:</td>
            <td>{{ form.facility }}</td>
        </tr>
        <tr>
            <td>Role:</td>
            <td>{{ form.role }}</td>
        </tr>
    </table>
    <input type="submit" name="submit" value="Return to Login" class="btn btn-primary">
    </form>
</fieldset>
{% endblock %}

register/templates/register/facility_list.html
{% extends 'login/base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table width="100%">
        <tr>
            <td>School Name: {{ form.name }}</td>
            <td>District: {{ form.district }}</td>
            <td>Island: {{ form.island }}</td>
            <td><input type="submit" value="Filter" name="submit" class="btn btn-primary"></td>
        </tr>
        </table>
    </form>
    <table class="table table-striped">
    <tr>
        <th>School Name</th>
        <th>Address</th>
        <th>City</th>
        <th>Zip</th>
        <th>Phone</th>
        <th>Total Enrollment</th>
        <th>Compliant</th>
    </tr>
    {% for facility in object_list %}
        <tr>
            <td><a href="{% url 'register:facilitylanding' facility.id%}"> {{ facility.name }}</a></td>
            <td>{{ facility.street }}</td>
            <td>{{ facility.city }}</td>
            <td>{{ facility.zip }}</td>
            <td>{{ facility.phone }}</td>
            <td>{{ facility.total_enrolled }}</td>
            <td>
                {% if facility.compliant %}
                <span class="glyphicon glyphicon-ok"></span>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>



    <ul class="pager">

            {% if object_list.has_previous %}
                <li class="previous"><a href="?page={{ object_list.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li><a href="{% url 'register:facilityinput' %}">Create Facility</a></li>
    {% if request.session.role == 1 %}
    |
    <li> <a href="{% url 'reportviewing:master12b' %}">Generate Master Grade School Report</a></li>
    |
    <li><a href="{% url 'reportviewing:master12a' %}">Generate Master Pre K Report</a></li>
    {% endif %}
            {% if object_list.has_next %}
               <li class="next"> <a href="?page={{ object_list.next_page_number }}">Next</a></li>
            {% endif %}



    </ul>
{% endblock %}

register/templates/register/facilityinput.html
{% extends 'login/base.html' %}
{% load staticfiles %}

{% block content %}
    {% if request.session.role == 1 %}
<fieldset class="login">
    <legend class="login">Create Facility</legend>
<form action="" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-xs-6">
            <div class="form-group">
                <label for="name">Name:</label>
               {{ form.name }}
            </div>
            <div class="form-group">
                <label for="street">Street:</label>
               {{ form.street }}
            </div>
        </div>
        <div class="col-xs-6">
            <img src="{% static "login/stop_flu_at_school.jpg" %}">
        </div>
    </div>
    <div class="form-group">
        <label for="zip">Zip:</label>
       {{ form.zip }}
    </div>
    <div class="form-group">
        <label for="city">City:</label>
       {{ form.city }}
    </div>
    <div class="form-group">
        <label for="phone">Phone:</label>
       {{ form.phone }}
    </div>
    <div class="form-group">
        <label for="fax">Fax:</label>
       {{ form.fax }}
    </div>
    <div class="form-group">
        <label for="email">E-Mail:</label>
       {{ form.email }}
    </div>
    <div class="form-group">
        <label for="has_pre_k">Has pre k:</label>
       {{ form.has_pre_k }}
    </div>
    <div class="form-group">
        <label for="is_only_pre_k">Is only pre k:</label>
       {{ form.is_only_pre_k }}
    </div>
    <div class="form-group">
        <label for="island">Island:</label>
       {{ form.island }}
    </div>
    <div class="form-group">
        <label for="district">District:</label>
       {{ form.district }}
    </div>
    <div class="form-group">
        <label for="lowest_grade">Lowest Grade:</label>
       {{ form.lowest_grade }}
    </div>
    <div class="form-group">
        <label for="highest_grade">Highest Grade:</label>
       {{ form.highest_grade }}
    </div>
    <input type="submit" name="submit" value="Submit" class="btn btn-primary">
</form>
</fieldset>
        {% else %}
        <h1>You Are Not Authorized to be here</h1>
    {% endif %}
{% endblock %}

register/templates/register/facilitylanding.html
{% extends 'login/base.html' %}
{% block content %}
<fieldset class="login">
    <legend style="text-align: center;">{{ f.name }}</legend>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Address</th>
            <th>City</th>
            <th>Zip</th>
            <th>Island</th>
            <th>District</th>
            <th>Phone</th>
            <th>Fax</th>
            <th>Principal/Director</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ f.street }}</td>
            <td>{{ f.city }}</td>
            <td>{{ f.zip }}</td>
            <td>{{ d.island }}</td>
            <td>{{ f.district }}</td>
            <td>{{ f.phone }}</td>
            <td>{{ f.fax }}</td>
            <td>{{ p }}</td>
        </tr>
        </tbody>
    </table>

    {% if f.is_only_pre_k != True %}
    <table class="table table-striped">
        <tr>
            <th>Lowest Grade</th>
            <th>Highest Grade</th>
            {% if f.lowest_grade_id == 2 %}
                <th>Kindergarten Enrollment</th>
            {% endif %}
            {% if f.lowest_grade_id <= 9 and f.highest_grade_id >= 9  %}
                <th>7th Grade Enrollment</th>
                {% endif %}
            <th>Total Enrollment</th>
        </tr>
        <tr>
            <td>{{ f.lowest_grade }}</td>
            <td>{{ f.highest_grade }}</td>
            {% if f.lowest_grade_id == 2 %}
                <td>{{ f.kinder_enroll }}</td>
            {% endif %}
            {% if f.lowest_grade_id <= 9 and f.highest_grade_id >= 9  %}
                <td>{{ f.seventh_grade_enroll }}</td>
                {% endif %}
            <td>{{ f.total_enrolled }}</td>
        </tr>
    </table>
    {% endif %}

    {% if f.has_pre_k %}
        <table class="table table-striped">
            <tr>
                <th>Under 19 Months</th>
                <th>19 Months and Over</th>
                <th>Total in Pre-K</th>
            </tr>
            <tr>
                <td>{{ f.under_19_months }}</td>
                <td>{{ f.over_19_months }}</td>
                <td>{{ f.total_prek }}</td>
            </tr>
        </table>
    {% endif %}

    <form action="" method="post">
    <table width="100%">
                {% csrf_token %}
        <tr>
            <td align="center"><a href="{% url 'register:modify' f.id%}" class="btn btn-primary" role="button">Modify Facility Information</a></td>
                {% if f.has_pre_k %}
                <td align="center"><button class="btn btn-primary" type="submit" name="12a">Create PreK Report</button></td>
                 {% endif %}
                {% if not f.is_only_pre_k %}
                <td align="center"><button class="btn btn-primary" type="submit" name="12b">Create Grade School Report</button></td>
                {% endif %}
                <td><button class="btn btn-primary" type="submit" name="Med">Medical Exemptions</button></td>
                <td><button class="btn btn-primary" type="submit" name="Rel">Religious Exemptions</button></td>
                <td><button class="btn btn-primary" type="submit" name="Ex">Exemptions</button></td>
                <td><button class="btn btn-primary" type="submit" name="All">All Students</button></td>
            <tr>
        </tr>
    </table>
    </form>
{% endblock %}

register/templates/register/modify_user.html
{% extends 'login/base.html' %}
{% load staticfiles %}

{% block content %}
 <fieldset class="login">
    <legend class="login">Modify User</legend>
    <form action="" method="post">
        {% csrf_token %}
    <div class="row">
        <div class="col-xs-6">
            <div class="form-group">
                <label for="fname">First Name:</label>
               {{ form.fname }}
            </div>
            <div class="form-group">
                <label for="mname">Middle Name:</label>
               {{ form.mname }}
            </div>
        </div>
        <div class="col-xs-6">
            <img src="{% static "login/vax_to_school.jpg" %}">
        </div>
    </div>
    <div class="form-group">
        <label for="lname">Last Name:</label>
       {{ form.lname }}
    </div>
    <div class="form-group">
        <label for="phone">Phone:</label>
       {{ form.phone }}
    </div>
    <div class="form-group">
        <label for="fax">Fax:</label>
       {{ form.fax }}
    </div>
    <div class="form-group">
        <label for="title">Title:</label>
       {{ form.title }}
    </div>
    <div class="form-group">
        <label for="user">User:</label>
       {{ form.user }}
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
       {{ form.password }}
    </div>
    {% if request.session.role == 1 %}
    <div class="form-group">
        <label for="facility">Facility:</label>
       {{ form.facility }}
    </div>
    <div class="form-group">
        <label for="role">Role</label>
       {{ form.role }}
    </div>
    <div class="form-group">
        <label for="verify">Verify:</label>
       {{ form.verify }}
    </div>
    {% endif %}
        <button class="btn btn-primary" type="submit" name="Change">Change</button>
        {% if request.session.role == 1 %}
        <button class="btn btn-primary" type="submit" name="Delete">Delete</button>
        {% else %}
        <button class="btn btn-primary" type="submit" name="Drop">Remove User</button>
        {% endif %}
    </form>
</fieldset>
{% endblock %}

register/templates/register/person_list.html
{% extends 'login/base.html' %}
{% block content %}
<h3>Manage User</h3>
    <form action="" method="post">
    {% csrf_token %}
    <table>
            <tr>
                <td>Last Name: {{ form.lname }}</td>
                <td><input type="submit" name="submit" value="Filter" class="btn btn-primary"></td>
            </tr>
        </table>
    </form>
    <table class="table table-striped">
        <tr>
            <th>Name</th>
            <th>Facility</th>
            <th>Role</th>
            <th>Verified</th>
        </tr>
    {% for person in object_list %}
        <tr>
            <td><a href="{% url 'register:modifyuser' person.id%}"> {{ person }}</a></td>
            <td>{{ person.facility }}</td>
            <td>{{ person.role }}</td>
            <td>{{ person.verified }}</td>
        </tr>
    {% endfor %}
    </table>
    <ul class="pager">

            {% if object_list.has_previous %}
                <li class="previous"><a href="?page={{ object_list.previous_page_number }}">Previous</a></li>
    {% endif %}
    <li><a href="{% url 'login:landingpage' %}">Return to Home</a><li>
    {% if object_list.has_next %}
               <li class="next"> <a href="?page={{ object_list.next_page_number }}">Next</a></li>
            {% endif %}
{% endblock %}