depthealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^reportviewing/', include('reportviewing.urls', namespace="reportviewing")),
    url(r'^reportinput/', include('reportinput.urls', namespace="reportinput")),
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^admin/', include(admin.site.urls)),
]

faq/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^category/',views.category, name='category'),
    url(r'^(?P<category_id>[0-9]+)/questions', views.faq, name='questions')
]

login/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^$',views.loginscreen, name='login'),
    url(r'^landingpage',views.landingpage, name='landingpage'),
    url(r'^logout', views.logout_view, name='logout'),
    url(r'^reset', views.resetpassword, name='reset')
]

urlpatterns += staticfiles_urlpatterns()

reportinput/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = [
    url(r'epi12a',views.epi12a, name='epi12a'),
    url(r'epi12b',views.epi12b, name='epi12b'),
    url(r'landing12a', views.landing12a, name='landing12a'),
    url(r'landing12b', views.landing12b, name='landing12b'),
    url(r'complete', views.complete, name='complete'),
    url(r'^(?P<student_id>[0-9]+)/update12a', views.update12a, name='update12a'),
    url(r'^(?P<student_id>[0-9]+)/update12b', views.update12b, name='update12b')
]

reportviewing/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns =[
    url(r'^(?P<student_id>[0-9]+)/removefromreport', views.removefromreport, name='removefromreport'),
    url(r'reportsbydate',views.reportsbydate,name='date'),
    url(r'^(?P<report_id>[0-9]+)/$',views.schoolreport,name='schoolreport'),
    url(r'^(?P<report_id>[0-9]+)/csva', views.createschoolcsva, name='csva'),
    url(r'^(?P<report_id>[0-9]+)/csvb', views.createschoolcsvb, name='csvb'),
    url(r'master12b', views.createmasterlist12b, name='master12b'),
    url(r'master12a', views.createmasterlist12a, name='master12a'),
    url(r'^students', views.listofstudents, name='students'),
    url(r'^studentfilter',views.studentfilter, name='studentfilter'),
    url(r'12apdf', views.epi12apdf, name='epi12apdf'),
    url(r'12bpdf', views.epi12bpdf, name='epi12bpdf'),
    url(r'removehighest', views.removehighestgrade, name='removehighest'),
    url(r'^importstudent/(?P<student_id>[0-9]+)', views.importstudent, name='importstudent'),
    url(r'importview', views.importview, name='importview')
]

reportviewing/models.py
from django.db import models

# Create your models here.

reportviewing/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from register.models import Facility, Person, Enrollment, Island, District
from reportinput.models import Student, Report
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django import forms
from itertools import chain
import datetime
import csv
# Create your views here.

@login_required
def removefromreport(request, student_id):
    student = Student.objects.get(pk = student_id)
    report = Report.objects.filter(student__id = student.pk).get(complete=False)
    if request.method =='POST':
        if 'confirm' in request.POST:
            report.student_set.remove(student)
            return HttpResponseRedirect(reverse('reportinput:complete'))
        else:
            return HttpResponseRedirect(reverse('reportviewing:reportbydate'))
    return render(request, 'reportviewing/confirm.html')

@login_required
def reportsbydate(request):
    p = Person.objects.get(pk = request.session['personpk'])
    try:
        r = Report.objects.filter(facility_id=p.facility_id)
    except (Report.DoesNotExist):
        return render(request, 'reportviewing/reportsbydate.html',{'error_message': "No reports for this facility",})
    return render(request,'reportviewing/reportsbydate.html',{'reports':r,})

@login_required
def schoolreport(request, report_id):
    r = Report.objects.get(pk = report_id)
    s = Student.objects.filter(report__id=r.pk)
    p = Person.objects.get(pk = request.session['personpk'])
    f = Facility.objects.get(pk = p.facility_id)
    if s:
        filterobject = s[0]
        if request.method == 'POST':
            if 'confirm' in request.POST:
                r.complete = True
                r.save()
                f.compliant = True
                f.save()
                return HttpResponseRedirect(reverse('login:landingpage'))
            else:
                if filterobject.enrollment_id == 1:
                    return HttpResponseRedirect(reverse('reportviewing:csva', args=(r.pk,)))
                else:
                    return HttpResponseRedirect(reverse('reportviewing:csvb', args=(r.pk,)))
    return render(request, 'reportviewing/schoolreport.html', {'students':s, 'report':r})

@login_required
def createschoolcsva(request, report_id):
    r = Report.objects.get(pk = report_id)
    students = Student.objects.filter(report__id=r.pk)
    f = Facility.objects.get(pk = r.facility_id)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="prekmaster.csv"'

    writer = csv.writer(response)
    writer.writerow([f.name,
                     'Report ID:',
                     r.id,
                     datetime.datetime.today()])
    writer.writerow(['Student ID',
                     'Name',
                     'Date of Birth',
                     'Age',
                     'No Shot Record',
                     'Medically Exempt',
                     'Religiously Exempt',
                     'Dtap 1',
                     'Dtap 2',
                     'Dtap 3',
                     'Dtap 4',
                     'Polio 1',
                     'Polio 2',
                     'Polio 3',
                     'Hib',
                     'HepB 1',
                     'HepB 2',
                     'HepB 3',
                     'MMR 1',
                     'Varicella 1',
                     'PE',
                     'TB',
                     'Notes'])
    for student in students:
        name = ''
        if student.mname == '':
            name = '{} {}'.format(student.fname, student.lname)
        else:
            name = '{} {} {}'.format(student.fname, student.mname, student.lname)
        writer.writerow([student.id,
                         name,
                         student.dateofbirth,
                         student.age,
                         student.noshotrecord,
                         student.exempt_med,
                         student.exempt_rel,
                         student.dtap1,
                         student.dtap2,
                         student.dtap3,
                         student.dtap4,
                         student.polio1,
                         student.polio2,
                         student.polio3,
                         student.hib,
                         student.hepb1,
                         student.hepb2,
                         student.hepb3,
                         student.mmr1,
                         student.varicella1,
                         student.pe,
                         student.tb,
                         student.notes])


    return response

@login_required
def createschoolcsvb(request, report_id):
    r = Report.objects.get(pk = report_id)
    students = Student.objects.filter(report__id=r.pk)
    f = Facility.objects.get(pk = r.facility_id)

    students = students.exclude(enrollment_id = 1)

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="gradeschoolmaster.csv"'

    writer = csv.writer(response)
    writer.writerow([f.name,
                     'Report ID:',
                     r.id,
                     datetime.datetime.today()])
    writer.writerow(['Student ID',
                     'Name',
                     'Date of Birth',
                     'Grade',
                     'No Shot Record',
                     'Medically Exempt',
                     'Religiously Exempt',
                     'Dtap 1',
                     'Dtap 2',
                     'Dtap 3',
                     'Dtap 4',
                     'Dtap 5',
                     'Polio 1',
                     'Polio 2',
                     'Polio 3',
                     'Polio 4',
                     'HepB 1',
                     'HepB 2',
                     'HepB 3',
                     'MMR 1',
                     'MMR 2',
                     'Varicella 1',
                     'Varicella 2',
                     'PE',
                     'TB',
                     'Notes'])
    for student in students:
        name = ''
        if student.mname == '':
            name = '{} {}'.format(student.fname, student.lname)
        else:
            name = '{} {} {}'.format(student.fname, student.mname, student.lname)
        writer.writerow([student.id,
                         name,
                         student.dateofbirth,
                         student.enrollment,
                         student.noshotrecord,
                         student.exempt_med,
                         student.exempt_rel,
                         student.dtap1,
                         student.dtap2,
                         student.dtap3,
                         student.dtap4,
                         student.dtap5,
                         student.polio1,
                         student.polio2,
                         student.polio3,
                         student.polio4,
                         student.hepb1,
                         student.hepb2,
                         student.hepb3,
                         student.mmr1,
                         student.mmr2,
                         student.varicella1,
                         student.varicella2,
                         student.pe,
                         student.tb,
                         student.notes])
    return response

@login_required
def createmasterlist12a(request):
    students = Student.objects.filter(enrollment_id = 1).order_by('facility')

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="prekmaster.csv"'

    writer = csv.writer(response)
    writer.writerow(['Student ID',
                     'Name',
                     'Date of Birth',
                     'School',
                     'Age',
                     'No Shot Record',
                     'Medically Exempt',
                     'Religiously Exempt',
                     'Dtap 1',
                     'Dtap 2',
                     'Dtap 3',
                     'Dtap 4',
                     'Polio 1',
                     'Polio 2',
                     'Polio 3',
                     'Hib',
                     'HepB 1',
                     'HepB 2',
                     'HepB 3',
                     'MMR 1',
                     'Varicella 1',
                     'PE',
                     'TB',
                     'Notes'])
    for student in students:
        name = ''
        if student.mname == '':
            name = '{} {}'.format(student.fname, student.lname)
        else:
            name = '{} {} {}'.format(student.fname, student.mname, student.lname)
        writer.writerow([student.id,
                         name,
                         student.dateofbirth,
                         student.facility,
                         student.age,
                         student.noshotrecord,
                         student.exempt_med,
                         student.exempt_rel,
                         student.dtap1,
                         student.dtap2,
                         student.dtap3,
                         student.dtap4,
                         student.polio1,
                         student.polio2,
                         student.polio3,
                         student.hib,
                         student.hepb1,
                         student.hepb2,
                         student.hepb3,
                         student.mmr1,
                         student.varicella1,
                         student.pe,
                         student.tb,
                         student.notes])
    return response

@login_required
def createmasterlist12b(request):

reportviewing/templates/reportviewing/confirm.html
{% extends 'login/base.html' %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
<h1 style="text-align: center">Confirm you want to remove {{ student }} from report</h1>
    <div style="text-align: center">
<button type="submit" class="btn btn-primary btn-lg" name="confirm">Yes</button>
<button type="submit" class="btn btn-primary btn-lg" name="mistake">No</button>
</div>
</form>
{% endblock %}

reportviewing/templates/reportviewing/csv.html
{% extends 'login/base.html' %}
{% block content %}
    <h1>You have created a new csv file</h1>
    <a href="{% url 'login.views.landingpage' %}">Return to Main Screen</a>
{% endblock %}

reportviewing/templates/reportviewing/import.html
{% extends 'login/base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    <table>
        <tr>
            <td>Student Id: </td>
            <td>{{ form.id }}</td>
            <td><button type="submit" class="btn btn-primary" name="search">Search</button></td>
        </tr>
    </table>
    {% if s %}
        <table width="100%">
        <tr>
            <th>Student ID</th>
            <th>Name</th>
            <th>Grade</th>
        </tr>

        <tr>
            <td><a href="{% url 'reportviewing:importstudent' s.id %}"> {{ s.id }}</a></td>
            <td>{{ s }}</td>
            <td>{{ s.enrollment }}</td>
        </tr>

        </table>
    {% else %}
        <p>No Student Found</p>
    {% endif %}
    </form>
{% endblock %}

reportviewing/templates/reportviewing/reportsbydate.html
{% extends 'login/base.html' %}
{% block content %}
    {% if reports %}
    {% csrf_token %}
    <h3>Reports</h3>
    <ul>
    {% for report in reports %}
        <li>
            <a href="{% url 'reportviewing:schoolreport' report.id %}">{{ report }}</a>
        </li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No Reports to Show</p>
    <a href="{% url 'login:landingpage' %}">Return to Main Screen</a>
    {% endif %}
{% endblock %}

reportviewing/templates/reportviewing/schoolreport.html
{% extends 'login/base.html' %}
{% block content %}
<h3>School Reports</h3>
    {% if students %}
        <form action="" method="post">
    {% csrf_token %}
    <table class="table table-striped">
        <tr>
            <th style="text-align: center">Name</th>
            <th style="text-align: center">Exemptions</th>
            <th style="text-align: center">Missing Vaccines</th>
            {% if not report.complete %}
                <th style="text-align: center">Remove Student From Report</th>
            {% endif %}
        </tr>
        {% for student in students %}
            <tr>
                {% if student.enrollment_id > 1 %}
                    <td style="text-align: center"><a href="{% url 'reportinput:update12b'  student.id%}">{{ student }}</a></td>
                {% elif student.enrollment_id == 1 %}
                    <td style="text-align: center"><a href="{% url 'reportinput:update12a' student.id %}">{{ student }}</a></td>
                {% endif %}

                <td style="text-align: center">
                    {% if student.exempt_med and student.exempt_rel %}
                        Medical and Religious
                    {% elif student.exempt_med %}
                        Medical
                    {% elif student.exempt_rel %}
                        Religious
                    {% else %}
                        None
                    {% endif %}
                </td>
                <td style="text-align: center">
                    {% if student.enrollment_id > 1 %}
                        {% if student.dtap1 %}
                            DTaP/DTP/DT/Td 1-5
                        {% elif student.dtap2 %}
                            DTaP/DTP/DT/Td 2-5
                        {% elif student.dtap3 %}
                            DTaP/DTP/DT/Td 3-5
                        {% elif student.dtap4 %}
                            DTaP/DTP/DT/Td 4-5
                        {% elif student.dtap5 %}
                            DTaP/DTP/DT/Td 5
                        {% endif %}
                        {% if student.polio1 %}
                            Polio 1-4
                        {% elif student.polio2 %}
                            Polio 2-4
                        {% elif student.polio3 %}
                            Polio 3-4
                        {% elif student.polio4 %}
                            Polio 4
                        {% endif %}
                        {% if student.hepb1 %}
                            HepB 1-3
                        {% elif student.hepb2 %}
                            HepB 2-3
                        {% elif student.hepb3 %}
                            HepB 3
                        {% endif %}
                        {% if student.mmr1 %}
                            MMR 1-2
                        {% elif student.mmr2 %}
                            MMR 2
                        {% endif %}
                        {% if student.varicella1 %}
                            Varicella 1-2
                        {% elif student.varicella2 %}
                            Varicella 2
                        {% endif %}
                        {% if student.pe %}
                            PE
                        {% endif %}
                        {% if student.tb %}
                            TB
                        {% endif %}
                    {% elif student.enrollment_id == 1 %}
                        {% if student.dtap1 %}
                            DTaP/DTP/DT 1-4
                        {% elif student.dtap2 %}
                            DTaP/DTP/DT 2-4
                        {% elif student.dtap3 %}
                            DTaP/DTP/DT 3-4
                        {% elif student.dtap4 %}
                            DTaP/DTP/DT 4
                        {% endif %}
                        {% if student.polio1 %}
                            Polio 1-3
                        {% elif student.polio2 %}
                            Polio 2-3
                        {% elif student.polio3 %}
                            Polio 3
                        {% endif %}
                        {% if student.hib %}
                            Hib
                        {% endif %}
                        {% if student.hepb1 %}
                            HepB 1-3
                        {% elif student.hepb2 %}
                            HepB 2-3
                        {% elif student.hepb3 %}
                            HepB 3
                        {% endif %}
                        {% if student.mmr1 %}
                            MMR 1
                        {% endif %}
                        {% if student.varicella1 %}
                            Varicella 1
                        {% endif %}
                        {% if student.pe %}
                            PE
                        {% endif %}
                        {% if student.tb %}
                            TB
                        {% endif %}
                    {% endif %}
                </td>
                {% if not report.complete %}
                    <td style="text-align: center"><a href="{% url 'reportviewing:removefromreport' student.id %}">Remove</a></td>
                {% endif %}
            </tr>
        {% endfor %}
        </table>
        <br />
    <input type="submit" value="Create CSV" class="btn btn-info">
        {% if request.session.role == 2 and not report.complete %}
    <input type="submit" value="Confirm" class="btn btn-info" name="confirm">
            {% endif %}
    </form>
    {% else %}
        <p>No Students In This Report</p>
    {% endif %}
{% endblock %}

reportviewing/templates/reportviewing/studentlist.html
{% extends 'login/base.html' %}
{% block content %}
   <h3>Students</h3>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>Last Name: {{ form.lname }}</td>
                <td><input type="submit" name="submit" value="Filter" class="btn btn-primary"></td>
                {% if request.session.role != 1 %}
                <td><input type="submit" name="remove" value="Remove Highest Grade" class="btn btn-primary"></td>
                <td><input type="submit" name="import" value="Import Students" class="btn btn-primary"></td>
                {% endif %}
            </tr>
        </table>
    </form>
    <br />
{% if students %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th style="text-align: center">Name</th>
            {% if request.session.role == 1 %}
            <th style="text-align: center">Facility</th>
            {% endif %}
            <th style="text-align: center">Notes</th>
        </tr>
        </thead>
        {% for student in students %}
        <tr>
            {% if student.enrollment_id > 1 %}
                    <td style="text-align: center"><a href="{% url 'reportinput:update12b'  student.id%}">{{ student }}</a></td>
            {% elif student.enrollment_id == 1 %}
                    <td style="text-align: center"><a href="{% url 'reportinput:update12a' student.id %}">{{ student }}</a></td>
            {% endif %}
            {% if request.session.role == 1 %}
            <td style="text-align: center">{{ student.facility }}</td>
            {% endif %}
            <td style="text-align: center">{{ student.notes }}</td>
        </tr>
    {% endfor %}
    </table>
    <ul class="pager">

            {% if students.has_previous %}
                <li class="previous"><a href="?page={{ students.previous_page_number }}">Previous</a></li>
            {% endif %}
    {% if students.has_next %}
               <li class="next"> <a href="?page={{ students.next_page_number }}">Next</a></li>
            {% endif %}
            {% else %}
        <h3>No students found</h3>
    {% endif %}
{% endblock %}

reportviewing/templates/reportviewing/students.html
{% extends 'login/base.html' %}
{% block content %}
    <h1 align="center">{{ f }}</h1>
    {% if n == 1 %}
        <h2 align="center">Medical Exemptions</h2>
    {% elif n == 2 %}
        <h2 align="center">Religious Exemptions</h2>
    {% elif n == 3 %}
        <h2 align="center">All Exemptions</h2>
    {% elif n == 4%}
        <h2 align="center">All Students</h2>
    {% endif %}
    {% if s %}
        <table class="table table-striped">
        <tr>
            <th>Name</th>
            <th>Exemptions</th>
            <th>Missing Vaccines</th>
        </tr>
        {% for student in s %}
            <tr>
                {% if student.enrollment_id > 1 %}
                    <td><a href="{% url 'reportinput:update12b'  student.id%}">{{ student }}</a></td>
                {% elif student.enrollment_id == 1 %}
                    <td><a href="{% url 'reportinput:update12a' student.id %}">{{ student }}</a></td>
                {% endif %}

                <td>
                    {% if student.exempt_med and student.exempt_rel %}
                        Medical and Religious
                    {% elif student.exempt_med %}
                        Medical
                    {% elif student.exempt_rel %}
                        Religious
                    {% else %}
                        None
                    {% endif %}
                </td>
                <td>
                    {% if student.enrollment_id > 1 %}
                        {% if student.dtap1 %}
                            DTaP/DTP/DT/Td 1-5
                        {% elif student.dtap2 %}
                            DTaP/DTP/DT/Td 2-5
                        {% elif student.dtap3 %}
                            DTaP/DTP/DT/Td 3-5
                        {% elif student.dtap4 %}
                            DTaP/DTP/DT/Td 4-5
                        {% elif student.dtap5 %}
                            DTaP/DTP/DT/Td 5
                        {% endif %}
                        {% if student.polio1 %}
                            Polio 1-4
                        {% elif student.polio2 %}
                            Polio 2-4
                        {% elif student.polio3 %}
                            Polio 3-4
                        {% elif student.polio4 %}
                            Polio 4
                        {% endif %}
                        {% if student.hepb1 %}
                            HepB 1-3
                        {% elif student.hepb2 %}
                            HepB 2-3
                        {% elif student.hepb3 %}
                            HepB 3
                        {% endif %}
                        {% if student.mmr1 %}
                            MMR 1-2
                        {% elif student.mmr2 %}
                            MMR 2
                        {% endif %}
                        {% if student.varicella1 %}
                            Varicella 1-2
                        {% elif student.varicella2 %}
                            Varicella 2
                        {% endif %}
                        {% if student.pe %}
                            PE
                        {% endif %}
                        {% if student.tb %}
                            TB
                        {% endif %}
                    {% elif student.enrollment_id == 1 %}
                        {% if student.dtap1 %}
                            DTaP/DTP/DT 1-4
                        {% elif student.dtap2 %}
                            DTaP/DTP/DT 2-4
                        {% elif student.dtap3 %}
                            DTaP/DTP/DT 3-4
                        {% elif student.dtap4 %}
                            DTaP/DTP/DT 4
                        {% endif %}
                        {% if student.polio1 %}
                            Polio 1-3
                        {% elif student.polio2 %}
                            Polio 2-3
                        {% elif student.polio3 %}
                            Polio 3
                        {% endif %}
                        {% if student.hib %}
                            Hib
                        {% endif %}
                        {% if student.hepb1 %}
                            HepB 1-3
                        {% elif student.hepb2 %}
                            HepB 2-3
                        {% elif student.hepb3 %}
                            HepB 3
                        {% endif %}
                        {% if student.mmr1 %}
                            MMR 1
                        {% endif %}
                        {% if student.varicella1 %}
                            Varicella 1
                        {% endif %}
                        {% if student.pe %}
                            PE
                        {% endif %}
                        {% if student.tb %}
                            TB
                        {% endif %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
        <p>No students</p>
    {% endif %}
{% endblock %}