depthealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^faq/', include('faq.urls', namespace="faq")),
    url(r'^support/', include('support.urls', namespace="support")),
    url(r'^reportviewing/', include('reportviewing.urls', namespace="reportviewing")),
    url(r'^reportinput/', include('reportinput.urls', namespace="reportinput")),
    url(r'^register/', include('register.urls', namespace="register")),
    url(r'^login/', include('login.urls', namespace="login")),
    url(r'^admin/', include(admin.site.urls)),
]

faq/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from . import views

urlpatterns = [
    url(r'^category/',views.category, name='category'),
    url(r'^(?P<category_id>[0-9]+)/questions', views.faq, name='questions')
]

support/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = [
    url(r'createticket', views.createrequest, name='create'),
    url(r'openticket', views.viewrequests, name='open'),
    url(r'^r(?P<r_id>[0-9]+)/updateticket', views.updatesupport, name='update'),
    url(r'^r(?P<r_id>[0-9]+)/closeticket', views.closesupport, name='close')
]

support/models.py
from django.db import models
from register import models as p

# Create your models here.
class Status(models.Model):
    id = models.AutoField(primary_key=True)
    statustype = models.CharField(max_length=20)

    class Meta:
        db_table = 'status'

    def __str__(self):
        return self.statustype

class Supportrequest(models.Model):
    id = models.AutoField(primary_key=True)
    person = models.ForeignKey(p.Person)
    status = models.ForeignKey('Status')
    description = models.CharField(max_length=255)
    opendate = models.DateField()
    closedate = models.DateField(null = True, blank=True)

    class Meta:
        db_table = 'supportrequest'

support/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Supportrequest

class Request(forms.ModelForm):
    class Meta:
        model = Supportrequest
        fields = ['description']

support/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import Request
from .models import Supportrequest
from register.models import Person
from django.contrib.auth.decorators import login_required
import datetime
# Create your views here.
@login_required
def createrequest(request):
    if request.method == 'POST':
        form = Request(request.POST)
        if form.is_valid():
            desc = form.cleaned_data['description']
            sr = Supportrequest(person_id=request.session['personpk'],status_id=1,description=desc, opendate=datetime.datetime.today())
            sr.save()
            return HttpResponseRedirect(reverse('support:open'))
    else:
        form = Request()
    return render(request, 'support/createsupport.html', {'form':form,})

@login_required
def viewrequests(request):
    p = Person.objects.get(pk=request.session['personpk'])
    if p.facility_id == 1:
        tickets = Supportrequest.objects.exclude(status_id=3)
    else:
        tickets = Supportrequest.objects.filter(person_id=p.pk)
    return render(request,'support/opentickets.html',{'tickets':tickets})

@login_required
def updatesupport(request, r_id):
    sr = Supportrequest.objects.get(pk = r_id)
    sr.status_id = 2
    sr.save()
    return HttpResponseRedirect(reverse('support:open'))

@login_required
def closesupport(request, r_id):
    sr = Supportrequest.objects.get(pk = r_id)
    sr.status_id = 3
    sr.save()
    return HttpResponseRedirect(reverse('support:open'))

support/templates/support/createsupport.html
{% extends 'login/base.html' %}
{% block content %}
<fieldset class="login">
	<legend class="login">Create Support Ticket</legend>
    <form action="" method="post">
        {% csrf_token %}
        <label>Description:</label><br />
        <textarea class="form-control" rows="5" id="id_description" name="description"></textarea>
        <input type="submit" name="submit" value="Submit" class="btn btn-primary">
    </form>
</fieldset>
{% endblock %}

support/templates/support/opentickets.html
{% extends 'login/base.html' %}
{% block content %}
 <fieldset class="login">
    <legend class="login">Support Requests
    {% csrf_token %}
    {% if request.session.role != 1 %}
        <a href="{% url 'support:create'%}" class="btn btn-primary">Create New Request</a>
    {% endif %}
    </legend>
    {% if tickets %}
        <table class="table table-striped">
            <thead>
              <tr>
                <th>Request Id</th>
                <th>Person</th>
                <th>Description</th>
                <th>Status</th>
                <th>Options</th>
              </tr>
            </thead>
            <tbody>
            {% for ticket in tickets %}
                    {% csrf_token %}
                        <tr>
                            <td>{{ ticket.id }}</td>
                            <td>{{ ticket.person }}</td>
                            <td>{{ ticket.description }}</td>
                            <td>{{ ticket.status }}</td>
                            {% if ticket.status_id != 3 %}
                                <td>
                            {% if request.session.role == 1 %}
                                {% if ticket.status_id != 2 %}
                                <a href="{% url 'support:update' ticket.id %}" class="btn btn-primary">Accept</a>
                            {% endif %}
                            {% endif %}
                                <a href="{% url 'support:close' ticket.id %}" class="btn btn-primary">Close</a>
                                </td>
                            {% endif %}
                        </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>No open tickets</p>
    {% endif %}
</fieldset>
{% endblock %} }}